Wrapper(Void),
Wrapper(RunTimeEnvironment),
Wrapper(ArchitectureSize),
Wrapper(Package),
Wrapper(Holds),

Wrapper(Entity),
Wrapper(Attribute),
Wrapper(Value),
Wrapper(UnnestEntity),
Wrapper(UnnestAttribute),
Wrapper(Message),
Wrapper(Row),
Wrapper(Column),
Wrapper(PosX),
Wrapper(PosY),

Wrapper(BlobType),
Wrapper(Natural),
Wrapper(Integer),
Wrapper(Float),
Wrapper(UTF8),

Wrapper(TripleIndex),
Wrapper(BlobIndex),
Wrapper(BinaryOntologyCodec),
Wrapper(BinaryOntologyCodecAux0),
Wrapper(BinaryOntologyCodecAux1),
